# Generated by Django 5.2.2 on 2025-06-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='address',
            field=models.TextField(),
        ),
    ]
