# Generated by Django 5.2.2 on 2025-06-24 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_slug_alter_cast_role'),
        ('theaters', '0003_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateTimeField()),
                ('silver_seats_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gold_seats_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('platinum_seats_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.theater')),
            ],
        ),
    ]
