# Generated by Django 5.2.2 on 2025-06-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0004_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
