# Generated by Django 5.2.2 on 2025-06-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('theaters', '0006_remove_seat_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingseat',
            name='showtime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theaters.showtime'),
        ),
    ]
