# Generated by Django 5.2.2 on 2025-06-30 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingseat_showtime'),
        ('theaters', '0006_remove_seat_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingseat',
            name='showtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theaters.showtime'),
        ),
    ]
