# Generated by Django 5.2.2 on 2025-06-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('genre', models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Horror', 'Horror'), ('Romance', 'Romance')], max_length=50, null=True)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('kannada', 'Kannada'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('Malayalam', 'Malayalam'), ('Bengali', 'Bengali'), ('Punjabi', 'Punjabi')], max_length=50, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Upcoming', 'Upcoming'), ('Released', 'Released')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to='movies/')),
            ],
        ),
    ]
